name: User story template
description: This template is used to submit user stories.
labels: ["user-story"]
assignees:
  - octocat
body:
  - type: input
    id: role
    attributes:
      label: As a
      placeholder: role
    validations:
      required: true
  - type: input
    id: function
    attributes:
      label: I need
      placeholder: function
    validations:
      required: true
  - type: input
    id: benefit
    attributes:
      label: So that
      placeholder: benefit
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details and Assumptions
      value: "Document what you know"
    validations:
      required: true
  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      value: "Given [some context]\nWhen [certain action is taken]\nThen [the outcome of action is observed]"
    validations:
      required: true
